version: '3'
services:
#  app:
#    build: .
#    command: bash -c "rm -f tmp/pids/server.pid && bundle e crono start && bundle exec rails s -p 3000 -b '0.0.0.0'"
#    tty: true
#    stdin_open: true
#    volumes:
#      - .:/myapp
#      - bundle:/myapp/vendor/bundle
#    env_file:
#      - .env
#    environment:
#      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
#    ports:
#      - 3000:3000
#
#  chrome:
#    image: selenium/standalone-chrome
#    ports:
#      - '4444:4444'
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 54320:5432
    environment:
      - POSTGRES_PASSWORD=password

volumes:
  bundle:
  db-data: