default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password

development:
  <<: *default
  database: odds_detector_development
  host: <%= ENV.fetch('DATABASE_HOST', '0.0.0.0') %>
  port: <%= ENV.fetch('DATABASE_PORT', '54320') %>

test:
  <<: *default
  database: odds_detector_test
  host: <%= ENV.fetch('DATABASE_HOST', '0.0.0.0') %>
  port: <%= ENV.fetch('DATABASE_PORT', '54320') %>

production:
  <<: *default
  database: odds_detector_production
  host: <%= ENV.fetch('DATABASE_URL', '127.0.0.1') %>